apiVersion: xl-deploy/v1
kind: Applications
spec:
  - directory: Applications/backstage
    children:
      - name: test-cmd
        type: udm.Application
        lastVersion: 1.0.0
        children:
          - name: 1.0.0
            type: udm.DeploymentPackage
            deployables:
              - name: test-cmd
                type: cmd.Command
                commandLine: echo test
---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
  - directory: Infrastructure/backstage
    children:
      - name: test-localhost
        type: overthere.LocalHost
        os: UNIX
---
apiVersion: xl-deploy/v1
kind: Environments
spec:
  - directory: Environments/backstage
    children:
      - name: test-environment
        type: udm.Environment
        members:
          - Infrastructure/backstage/test-localhost